Repository mikaelvincent/Fitness-AI, pull requests merged in 2024-12, with the labels that each got.

#22 Enhancements for Forgot Password, Password Reset, and Routing Fixes
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/components/authentication/forms/ForgotPasswordForm.tsx
  frontend/src/components/authentication/forms/LoginForm.tsx
  frontend/src/components/authentication/forms/RegisterForm.tsx
  frontend/src/components/authentication/forms/ResetPasswordForm.tsx
  frontend/src/components/authentication/forms/VerifyEmailForm.tsx
  frontend/src/components/protected-routes/ProtectedRoute.tsx
  frontend/src/components/ui/toast.tsx
  frontend/src/components/ui/toaster.tsx
  frontend/src/hooks/use-toast.ts
  frontend/src/layout/MainLayout.tsx
  frontend/src/pages/ForgotPassword.tsx
  frontend/src/pages/Register.tsx
  frontend/src/pages/ResetPassword.tsx
  frontend/src/pages/VerifyEmail.tsx
  frontend/src/services/auth/resetPassword.ts
  frontend/src/utils/schema/ResetPasswordSchema.ts
Labels: enhancement

#21 Update Symfony Dependencies to Resolve Security Vulnerabilities
  api-server/composer.json
  api-server/composer.lock
Labels: dependencies

#23 Implement email-only registration initiation
  api-server/app/Http/Controllers/Auth/RegisteredUserController.php
  api-server/app/Models/RegistrationToken.php
  api-server/database/migrations/2024_12_01_141408_create_registration_tokens_table.php
  api-server/routes/api.php
Labels: enhancement

#24 Send Verification Email During Registration
  api-server/app/Http/Controllers/Auth/RegisteredUserController.php
  api-server/app/Notifications/RegistrationTokenNotification.php
Labels: enhancement

#25 Add resend verification email functionality
  api-server/app/Http/Controllers/Auth/RegisteredUserController.php
  api-server/routes/api.php
Labels: enhancement

#26 Add registration token validation endpoint
  api-server/app/Http/Controllers/Auth/RegisteredUserController.php
  api-server/app/Models/RegistrationToken.php
  api-server/routes/api.php
Labels: enhancement

#27 Add endpoint for user registration completion
  api-server/app/Http/Controllers/Auth/RegisteredUserController.php
Labels: enhancement

#28 Add cleanup task for expired registration tokens
  api-server/app/Console/Commands/CleanUpExpiredRegistrationTokens.php
  api-server/app/Console/Kernel.php
Labels: enhancement

#31 Implement Enhanced Registration and Password Management
  api-server/app/Actions/Fortify/UpdateUserProfileInformation.php
  api-server/app/Console/Commands/CleanUpExpiredRegistrationTokens.php
  api-server/app/Console/Kernel.php
  api-server/app/Http/Controllers/Auth/AuthenticatedSessionController.php
  api-server/app/Http/Controllers/Auth/ChangePasswordController.php
  api-server/app/Http/Controllers/Auth/EmailVerificationController.php
  api-server/app/Http/Controllers/Auth/PasswordResetController.php
  api-server/app/Http/Controllers/Auth/RegisteredUserController.php
  api-server/app/Http/Controllers/Auth/TokenRefreshController.php
  api-server/app/Http/Controllers/Auth/TwoFactorAuthenticationController.php
  api-server/app/Models/RegistrationToken.php
  api-server/app/Models/User.php
  api-server/app/Notifications/RegistrationTokenNotification.php
  api-server/app/Notifications/VerifyEmailNotification.php
  api-server/config/fortify.php
  api-server/database/migrations/2024_12_01_141408_create_registration_tokens_table.php
  api-server/routes/api.php
  api-server/tests/Feature/EmailVerificationTest.php
  api-server/tests/Feature/LoginTest.php
  api-server/tests/Feature/PasswordResetTest.php
  api-server/tests/Feature/RegistrationTest.php
  docs/api-server/docs/collection.json
  docs/api-server/docs/index.html
  docs/api-server/docs/openapi.yaml
Labels: documentation, enhancement

#33 Add and Enhance Comprehensive Test Coverage for Core Features
  api-server/app/Http/Controllers/Auth/TwoFactorController.php
  api-server/app/Http/Kernel.php
  api-server/app/Models/RegistrationToken.php
  api-server/app/Notifications/RegistrationTokenNotification.php
  api-server/database/factories/RegistrationTokenFactory.php
  api-server/tests/Feature/Auth/PasswordControllerTest.php
  api-server/tests/Feature/Auth/RegistrationControllerTest.php
  api-server/tests/Feature/Auth/SessionControllerTest.php
  api-server/tests/Feature/Auth/TokenControllerTest.php
  api-server/tests/Feature/Auth/TwoFactorControllerTest.php
  api-server/tests/Feature/ChangePasswordTest.php
  api-server/tests/Feature/Console/CleanUpExpiredRegistrationTokensTest.php
  api-server/tests/Feature/LoginTest.php
  api-server/tests/Feature/LogoutTest.php
  api-server/tests/Feature/PasswordResetTest.php
  api-server/tests/Feature/RateLimitingTest.php
  api-server/tests/Feature/RegistrationTest.php
  api-server/tests/Feature/TokenRefreshTest.php
  api-server/tests/Feature/TwoFactorAuthenticationTest.php
  api-server/tests/Unit/Middleware/RateLimitingMiddlewareTest.php
  api-server/tests/Unit/Models/RegistrationTokenTest.php
  api-server/tests/Unit/Models/UserTest.php
  api-server/tests/Unit/Notifications/RegistrationTokenNotificationTest.php
  api-server/tests/Unit/Notifications/ResetPasswordNotificationTest.php
Labels: enhancement

#34 Refactor Rate Limiting, Update Routes, and Implement Comprehensive Tests
  api-server/app/Http/Controllers/Auth/AuthenticatedSessionController.php
  api-server/app/Http/Controllers/Auth/ChangePasswordController.php
  api-server/app/Http/Controllers/Auth/PasswordController.php
  api-server/app/Http/Controllers/Auth/PasswordResetController.php
  api-server/app/Http/Controllers/Auth/RegisteredUserController.php
  api-server/app/Http/Controllers/Auth/RegistrationController.php
  api-server/app/Http/Controllers/Auth/SessionController.php
  api-server/app/Http/Controllers/Auth/TokenController.php
  api-server/app/Http/Controllers/Auth/TokenRefreshController.php
  api-server/app/Http/Controllers/Auth/TwoFactorAuthenticationController.php
  api-server/app/Http/Controllers/Auth/TwoFactorController.php
  api-server/app/Http/Kernel.php
  api-server/app/Http/Middleware/RateLimitingMiddleware.php
  api-server/app/Models/RegistrationToken.php
  api-server/app/Notifications/RegistrationTokenNotification.php
  api-server/config/ratelimiter.php
  api-server/database/factories/RegistrationTokenFactory.php
  api-server/routes/api.php
  api-server/tests/Feature/Auth/PasswordControllerTest.php
  api-server/tests/Feature/Auth/RegistrationControllerTest.php
  api-server/tests/Feature/Auth/SessionControllerTest.php
  api-server/tests/Feature/Auth/TokenControllerTest.php
  api-server/tests/Feature/Auth/TwoFactorControllerTest.php
  api-server/tests/Feature/ChangePasswordTest.php
  api-server/tests/Feature/Console/CleanUpExpiredRegistrationTokensTest.php
  api-server/tests/Feature/LoginTest.php
  api-server/tests/Feature/LogoutTest.php
  api-server/tests/Feature/PasswordResetTest.php
  api-server/tests/Feature/RateLimitingTest.php
  api-server/tests/Feature/RegistrationTest.php
  api-server/tests/Feature/TokenRefreshTest.php
  api-server/tests/Feature/TwoFactorAuthenticationTest.php
  api-server/tests/Unit/Middleware/RateLimitingMiddlewareTest.php
  api-server/tests/Unit/Models/RegistrationTokenTest.php
  api-server/tests/Unit/Models/UserTest.php
  api-server/tests/Unit/Notifications/RegistrationTokenNotificationTest.php
  api-server/tests/Unit/Notifications/ResetPasswordNotificationTest.php
  docs/api-server/docs/collection.json
  docs/api-server/docs/index.html
  docs/api-server/docs/openapi.yaml
Labels: documentation, enhancement

#35 Dashboard
  frontend/README.md
  frontend/index.html
  frontend/package-lock.json
  frontend/package.json
  frontend/public/Light Mode - No Text.svg
  frontend/public/logo_Dark Mode - No text.svg
  frontend/public/no_text.svg
  frontend/src/App.tsx
  frontend/src/assets/images/dark_mode.svg
  frontend/src/assets/images/light_mode.svg
  frontend/src/assets/images/logo_Dark Mode - No Text.svg
  frontend/src/assets/images/logo_Dark Mode.svg
  frontend/src/assets/images/logo_Light Mode - No Text.svg
  frontend/src/assets/images/logo_Light Mode.svg
  frontend/src/assets/images/no_text.svg
  frontend/src/components/navbar/responsive-nav.tsx
  frontend/src/components/theme/ModeToggle.tsx
  frontend/src/components/ui/logo.tsx
  frontend/src/components/ui/sheet.tsx
  frontend/src/layout/AuthLayout.tsx
  frontend/src/layout/MainLayout.tsx
  frontend/src/pages/Chat.tsx
  frontend/src/pages/Dashboard.tsx
  frontend/src/pages/Home.tsx
  frontend/src/pages/Profile.tsx
  frontend/src/pages/Progress.tsx
Labels: enhancement

#38 Remove unused columns and ensure email verification consistency
  api-server/app/Actions/Fortify/CreateNewUser.php
  api-server/app/Http/Controllers/Auth/RegistrationController.php
  api-server/database/factories/UserFactory.php
  api-server/database/migrations/2014_10_12_000000_create_users_table.php
  api-server/database/migrations/2019_08_19_000000_create_failed_jobs_table.php
  api-server/tests/Unit/Models/UserTest.php
Labels: enhancement

#39 Remove user data from API responses and adjust tests
  api-server/app/Http/Controllers/Auth/RegistrationController.php
  api-server/app/Http/Controllers/Auth/SessionController.php
  api-server/tests/Feature/Auth/RegistrationControllerTest.php
  api-server/tests/Feature/Auth/SessionControllerTest.php
  docs/api-server/docs/collection.json
  docs/api-server/docs/index.html
  docs/api-server/docs/openapi.yaml
Labels: documentation, enhancement

#44 Add dynamic profile schema for flexible user attributes
  api-server/database/migrations/2024_12_08_074924_create_user_profiles_table.php
  api-server/database/migrations/2024_12_08_075147_create_user_profile_attributes_table.php
Labels: enhancement

#45 Implement dynamic profile models and repository
  api-server/app/Models/UserProfile.php
  api-server/app/Models/UserProfileAttribute.php
  api-server/app/Repositories/DynamicProfileAttributesRepository.php
Labels: enhancement

#53 Remove email_verified_at column from User model and related references
  api-server/app/Actions/Fortify/CreateNewUser.php
  api-server/app/Models/User.php
  api-server/database/factories/UserFactory.php
  api-server/database/migrations/2014_10_12_000000_create_users_table.php
  api-server/tests/Unit/Models/UserTest.php
Labels: enhancement

#55 Add comprehensive Activity module with hierarchical support
  api-server/app/Http/Controllers/Activities/ActivityController.php
  api-server/app/Http/Controllers/User/UserAttributeController.php
  api-server/app/Models/Activity.php
  api-server/app/Models/User.php
  api-server/database/factories/ActivityFactory.php
  api-server/database/migrations/2024_12_11_163806_create_user_attributes_table.php
  api-server/database/migrations/2024_12_12_123513_create_activities_table.php
  api-server/routes/api.php
  api-server/tests/Feature/Activities/ActivityControllerTest.php
  api-server/tests/Feature/User/UserAttributeControllerTest.php
  api-server/tests/Unit/Models/ActivityTest.php
  docs/api-server/docs/collection.json
  docs/api-server/docs/index.html
  docs/api-server/docs/openapi.yaml
Labels: documentation, enhancement

#61 Add Chat Feature with Tool Integration and Streaming
  api-server/.env.example
  api-server/app/Http/Controllers/Activities/ActivityController.php
  api-server/app/Http/Controllers/Chat/ChatController.php
  api-server/app/Http/Controllers/User/UserAttributeController.php
  api-server/app/Providers/AppServiceProvider.php
  api-server/app/Repositories/ActivityRepository.php
  api-server/app/Repositories/UserAttributeRepository.php
  api-server/app/Services/ActivityService.php
  api-server/app/Services/ChatContextService.php
  api-server/app/Services/ChatService.php
  api-server/app/Services/ChatToolService.php
  api-server/app/Services/UserAttributeService.php
  api-server/composer.json
  api-server/composer.lock
  api-server/config/openai.php
  api-server/routes/api.php
  docs/api-server/docs/collection.json
  docs/api-server/docs/index.html
  docs/api-server/docs/openapi.yaml
Labels: documentation, enhancement, dependencies

#63 Implement multiple tool calls and refactor tool handling
  api-server/app/Http/Controllers/Chat/ChatController.php
  api-server/app/Services/ChatService.php
  api-server/config/chatprompts.php
  api-server/config/chattools.php
Labels: enhancement

#64 Add endpoint for updating user name
  api-server/app/Http/Controllers/User/UserProfileController.php
  api-server/routes/api.php
  api-server/tests/Feature/User/UserProfileControllerTest.php
  docs/api-server/docs/collection.json
  docs/api-server/docs/index.html
  docs/api-server/docs/openapi.yaml
Labels: documentation, enhancement

#66 Enhance Two-Factor Authentication and Address Test Issues
  api-server/app/Http/Controllers/Auth/SessionController.php
  api-server/app/Http/Controllers/Auth/TwoFactorController.php
  api-server/tests/Feature/Auth/SessionControllerTest.php
  api-server/tests/Feature/Auth/TwoFactorControllerTest.php
Labels: enhancement

#67 Implement User Profile Retrieval Endpoint
  api-server/app/Http/Controllers/User/UserProfileController.php
  api-server/routes/api.php
  api-server/tests/Feature/User/UserProfileControllerTest.php
  docs/api-server/docs/collection.json
  docs/api-server/docs/index.html
  docs/api-server/docs/openapi.yaml
Labels: documentation, enhancement

#70 Fix ActivityTest to handle JSON encoding differences
  api-server/tests/Unit/Models/ActivityTest.php
Labels: enhancement

#74 Enhance Chat Context and System Prompts
  api-server/app/Services/ChatContextService.php
  api-server/app/Services/ChatService.php
  api-server/config/chatprompts.php
  api-server/config/chattools.php
Labels: enhancement

#82 Implement sliding expiration for API tokens
  api-server/app/Http/Controllers/Auth/RegistrationController.php
  api-server/app/Http/Controllers/Auth/SessionController.php
  api-server/app/Http/Controllers/Auth/TokenController.php
  api-server/app/Http/Kernel.php
  api-server/app/Http/Middleware/UpdateTokenExpiry.php
  api-server/routes/api.php
  api-server/tests/Feature/Auth/TokenControllerTest.php
  docs/api-server/docs/collection.json
  docs/api-server/docs/index.html
  docs/api-server/docs/openapi.yaml
Labels: documentation, enhancement

#85 Implement async processing and update documentation
  api-server/.env.example
  api-server/app/Http/Controllers/Chat/ChatController.php
  api-server/app/Jobs/ProcessChatRequest.php
  api-server/database/migrations/2024_12_17_205504_create_jobs_table.php
  api-server/routes/api.php
  docs/api-server/docs/collection.json
  docs/api-server/docs/index.html
  docs/api-server/docs/openapi.yaml
  docs/api-server/setup.md
Labels: documentation, enhancement
